version: '3.3'
services:
  mysql_inventory:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'inventory-service'
      MYSQL_USER: 'barney'
      MYSQL_PASSWORD: 'barney'
      MYSQL_ROOT_PASSWORD: 'barney'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - my-db1:/var/lib/mysql
  
  mysql_order:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'order-service'
      MYSQL_USER: 'barney'
      MYSQL_PASSWORD: 'barney'
      MYSQL_ROOT_PASSWORD: 'barney'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db2:/var/lib/mysql

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
  my-db1:
  my-db2:
